spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/links_database
    username: al
    password: aladmin
    driver-class-name: com.mysql.cj.jdbc.Driver