spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.OracleDialect
    open-in-view: false
    database: oracle
  datasource:
    url: jdbc:oracle:thin:@//DESKTOP-LG1EAKI.mshome.net:1521/xe
    username: system
    password: root
    driver-class-name: oracle.jdbc.OracleDriver

server-host: http://localhost:8080